# permissions for end users to edit lobbies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: lobby-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder-demo
    app.kubernetes.io/part-of: kubebuilder-demo
    app.kubernetes.io/managed-by: kustomize
  name: lobby-editor-role
rules:
- apiGroups:
  - srvptt2.online.my.domain
  resources:
  - lobbies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - srvptt2.online.my.domain
  resources:
  - lobbies/status
  verbs:
  - get
