apiVersion: srvptt2.online.my.domain/v1beta1
kind: Lobby
metadata:
  labels:
    app.kubernetes.io/name: lobby
    app.kubernetes.io/instance: lobby-sample
    app.kubernetes.io/part-of: kubebuilder-demo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebuilder-demo
  name: lobby-sample
spec:
  # TODO(user): Add fields here
